name: rep_rise
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  health: ^13.2.1
  fl_chart: ^1.1.1
  permission_handler: ^12.0.1
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0
  provider: ^6.1.5+1
  jwt_decoder: ^2.0.1
  get_it: ^9.2.0
  google_fonts: ^6.3.3
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: NataSans
      fonts:
        - asset: assets/fonts/static/NataSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/static/NataSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/static/NataSans-Light.ttf
          weight: 300
        - asset: assets/fonts/static/NataSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/static/NataSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/NataSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/NataSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/NataSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/static/NataSans-Black.ttf
          weight: 900


  uses-material-design: true
